[package]
name = "hello-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.15"
borsh = "1.5.3"

[dev-dependencies]
solana-program-test = "1.18.15"
solana-sdk = "1.18.15"

[lib]
crate-type = ["cdylib", "lib"]